learn_app/admin1/urls.py
from django. urls import path
from . import views
app_name= 'admin1'

urlpatterns = [
    path('homepage/',views.getadmin1,name="homepage"),
    path('master3/',views.getmaster3,name="master3"),
    path('manageresellers/',views.getmanageresellers,name="manageresellers"),
    path('activeresellers/',views.getactiveresellers,name="activeresellers"),
    path('rejectedresellers/',views.getrejectedresellers,name="rejectedresellers"),
    path('sum/',views.getsum,name="sum"),
]

learn_app/customer/urls.py
from django. urls import path
from . import views
app_name='customer'

urlpatterns = [
    path('master1/',views.getmaster,name="master1"),
    path('homepage1/',views.getcustomerhomepage,name="homepage1"),
    path('signup/',views.getcustomersignup,name="signup"),
    path('verifyotp/',views.getcustomerverifyotp,name="verifyotp"),
    path('login/',views.getcustomerlogin,name="login"),
    path('profile/',views.getcustomerprofile,name="profile"),
    path('search/',views.getcustomers,name="search"),
    path('master2/',views.getmaster2,name="master2"),
    path('viewproduct/',views.getviewproduct,name="viewproduct"),
    path('loginhomepage/',views.getloginhomepage,name="loginhomepage"),
    path('bag/',views.getbag,name="bag"),
    path('buynow/',views.getbuynow,name="buynow"),
]

learn_app/learn_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin1/', include('admin1.urls')),
    path('reseller/', include('reseller.urls')),
    path('customer/', include('customer.urls')),
]+static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

learn_app/admin1/models.py
from django.db import models

# Create your models here.

learn_app/admin1/views.py
from django.shortcuts import render
from reseller.models import Reseller
# Create your views here.


def getadmin1(request):
    return render(request,"admin1/homepage.html")

def getmaster3(request):
    return render(request,"admin1/master3.html")

def getmanageresellers(request):
    reseller_data=Reseller.objects.filter(status='inactive')
    if request.method=="POST":
        seller_id=request.POST['reseller_id']
        reseller=Reseller.objects.get(id=seller_id)
        if 'approve' in request.POST:
            reseller.status='active'
        if 'reject' in request.POST:
            reseller.status='reject'
        reseller.save()
    return render(request,"admin1/manageresellers.html",{'resellers':reseller_data})

def getactiveresellers(request):
    reseller_data=Reseller.objects.filter(status='active')
    


    return render(request,"admin1/activeresellers.html",{'resellers':reseller_data})
 
def getrejectedresellers(request):
    reseller_data=Reseller.objects.filter(status='reject')
    return render(request,"admin1/rejectedresellers.html",{'resellers':reseller_data})

def getsum(request):
    result=""
    if request.method=="POST":
        num1=int(request.POST['frstnum'])
        num2=int(request.POST['scndnum'])
        result=num1+num2
    return render(request,"admin1/sum.html",{'res':result})
 
 

learn_app/admin1/templates/admin1/activeresellers.html
{% extends 'admin1/master3.html' %}

{% block content %}

{% load static %}


<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="col">request date</th>
                    <th scope="col">Company name <br>& Id</th>
                    <th scope="col">Email</th>
                    <th scope="col">Address</th>
                    <th scope="col">Mobile</th>
                    <th scope="col">Bank details <br>Bank name <br> Account no <br>Ifsc</th>
                    <th scope="col">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {% for reseller in resellers %}
                  <form action="" method="post">
                    {% csrf_token %}
                  <tr>
                  <td>{{reseller.request_date|date:'Y-m-d'}}</td>
                  <td>{{reseller.company_name}}<br>{{reseller.reg_id}}</td>
                  <td>{{reseller.email}}</td>
                  <td>{{reseller.address}}</td>
                  <td>{{reseller.mobile}}</td>
                  <td>{{reseller.branch_bank}} <br> {{reseller.account_number}} <br>{{reseller.ifsc_code}} </td>
                   <td>{{reseller.status}}</td>
                </tr></form>
                  {% endfor %}
                  
                </tbody>
              </table>




        </div>
    </div>
</div>





{% endblock %}

learn_app/admin1/templates/admin1/addresellers.html
{% extends 'admin1/master3.html' %}

{% block content %}

{% load static %}


<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="col">Request date</th>
                    <th scope="col">Company name <br>& Id</th>
                    <th scope="col">Email</th>
                    <th scope="col">Address</th>
                    <th scope="col">Mobile</th>
                    <th scope="col">Bank details <br>bank name  <br> Account no <br>Ifsc</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {% for reseller in resellers %}
                  <tr>
                    <td>{{reseller.request_date|date:'Y-m-d'}}</td>
                  <td>{{reseller.company_name}}<br>{{reseller.reg_id}}</td>
                  
                  <td>{{reseller.email}}</td>
                  <td>{{reseller.address}}</td>
                  <td>{{reseller.mobile}}</td>
                  <td>{{reseller.branch_bank}} <br> {{reseller.account_number}} <br>{{reseller.ifsc_code}} </td>
                   nj<td><button class="btn btn-success">active</button></td>
                  <td><button class="btn btn-danger">reject</button></td>
                
                </tr>
                  {% endfor %}
                </tbody>
              </table>




        </div>
    </div>
</div>







{% endblock %}

learn_app/admin1/templates/admin1/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body style="background-color: #adb5bb;">
<div class="container" >
  <div class="row">

<div class="col-12 col-sm-12 col-md-12 col-lg-12">

    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand"><img src="{% static 'images/LOGO1.jpg' %}" alt="" height="60px" width="100px"></a>
        <form class="form-inline">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"  style="width:300px;">
          <button style="margin-right:15px;" class="btn btn-outline-success my-2 my-sm-0" type="submit">search</button>
            <a href="{% url 'customer:login' %}"><button style="margin-right:10px ;width: 100px;" class="btn btn-warning">log in</button></a>
            <a href="{% url 'customer:signup' %}"><button style="  width: 100px;" class="btn btn-warning">sign up</button></a>
        </form>
      </nav>       
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(8, 56, 40);">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
              Electronics
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Mobile&accessories</a>
                <a class="dropdown-item" href="#">Laptop</a>
                <a class="dropdown-item" href="#">Speaker</a>
                <a class="dropdown-item" href="#">Camera</a>
                <a class="dropdown-item" href="#">Gaming&Accessories</a>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Tv&Appliances
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Television</a>
                <a class="dropdown-item" href="#">Washing machine</a>
                <a class="dropdown-item" href="#">Rafrigerators</a>
                <a class="dropdown-item" href="#">Kitchen&Applainces</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Sports
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Football</a>
                <a class="dropdown-item" href="#">Cricket</a>
                <a class="dropdown-item" href="#">Tennis</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Fashion
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Mens</a>
                <a class="dropdown-item" href="#">Womens</a>
                <a class="dropdown-item" href="#">kids</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
  </div>
  </div>
</div>
<div class="container">
<div class="row">
    <div class="col- col-sm- col-md-4 col-lg-4"></div>
        <div class="col-12 col-sm-12 col-md-8 col-lg-8">
            <form>
                <h2>Log in</h2>
                <div class="form-group">
                  <label for="exampleInputEmail1">User name</label>
                  <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                  
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1">
                </div>
                
                <button type="submit" class="btn btn-success">log in</button><br><br>

                <a href="">forget password ?</a><br><br>
                <a href="">create an account</a><br> <br>

              </form>
        </div>

       <div class="container">
        <div class="row">
             
      
      <div style="background-color: rgb(179, 174, 174);" class="col-12 col-sm-12 col-md-6 col-lg-6">
      <h6>REGISTERED OFFICE ADDRESS</h6>
      <P>5th floor,crafit square,hilite buisiness park,<br>
      thondayadu,poovangal,kozhikode,kerala,670136
      </P>
      </div>
      <div style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2"><H6>POLICY</H6>
      <p>return policy,  <br> terms of use<br> security <br> privacy</p>
      </div>
      <div style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2">
      <h6>ABOUT AS</h6>
      <p> contact us <br> about as<br> careers<br> cybersquare<br> wholesale </p>
      </div>
      <div  style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2">
      <h6>SOCIAL</h6>
      <p>facebook<br> twitter<br> youtube</p>
      </div>
      <div style="background-color: rgb(117, 121, 121);" class="col-2 col-sm-3 col-md-4 col-lg-4"></div>
      <div style="background-color: rgb(117, 121, 121);" class="col-8 col-sm-6 col-md-4 col-lg-4">
        <img src="{% static 'images/visa.jpg' %}" alt=""height="75px" width="200px">
      </div>
      <div style="background-color: rgb(117, 121, 121);" class="col-2 col-sm-3 col-md-4 col-lg-4"></div>
      </div>
      
      </div>
      
      
      
      
      
      
                  
          <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>      
      
      
      </body>
      </html>
      

learn_app/admin1/templates/admin1/manageresellers.html
{% extends 'admin1/master3.html' %}

{% block content %}

{% load static %}


<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="col">Request date</th>
                    <th scope="col">Company name <br>& Id</th>
                    <th scope="col">Email</th>
                    <th scope="col">Address</th>
                    <th scope="col">Mobile</th>
                    <th scope="col">Bank details <br>bank name  <br> Account no <br>Ifsc</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {% for reseller in resellers %}
                  <form action="" method="post">
                    {% csrf_token %}
                  <tr>
                  <td>{{reseller.request_date|date:'Y-m-d'}}</td>
                  <td>{{reseller.company_name}}<br>{{reseller.reg_id}}</td>
                  <td>{{reseller.email}}</td>
                  <td>{{reseller.address}}</td>
                  <td>{{reseller.mobile}}</td>
                  <td>{{reseller.branch_bank}} <br> {{reseller.account_number}} <br>{{reseller.ifsc_code}} </td>
                  <td><button name="approve" class="btn btn-success">active</button></td>
                  <td><button name="reject" class="btn btn-danger">reject</button></td>
                <td><input type="hidden" name="reseller_id" value="{{reseller.id}}"></td>
                </tr></form>
                  {% endfor %}
                </tbody>
              </table>




        </div>
    </div>
</div>







{% endblock %}

learn_app/admin1/templates/admin1/master3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <nav class="navbar navbar-light" style="background-color: #0b8034;">
                <a class="navbar-brand"><img src="{% static 'images/LOGO1.jpg' %}" alt="" height="60px" width="100px"></a>
                 <div class="dropdown">
                    <div class="dropdown">
                      <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'images/profilelogo.jpg' %}" alt=""style="width:50px; height:50px;">
                      </button>
                    <div class="dropdown-menu">
                      <button class="dropdown-item" type="button">Change name</button>
                      <button class="dropdown-item" type="button">Change password</button>
                      <button class="dropdown-item" type="button">Log out</button>
                    </div>
                  </div>
              </nav>       
              </div>
              <div class="col-12 col-sm-12 col-md-12 col-lg-12">
              <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 119, 255);">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                  <div class="navbar-nav">
                    <a class="nav-link active" href="{% url 'admin1:manageresellers' %}">Manage resellers </a>
                    <a class="nav-link" href="{% url 'admin1:activeresellers' %}">Active resellers</a>
                    <a class="nav-link" href="{% url 'admin1:rejectedresellers' %}">Rejected resellers</a>
                
                  </div>
                </div>
              </nav>
              </div>
    </div>
  </div>
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>      

</body>
</html>

learn_app/admin1/templates/admin1/rejectedresellers.html
{% extends 'admin1/master3.html' %}

{% block content %}

{% load static %}
<div class="container">
  <div class="row">
      <div class="col-12 col-sm-12 col-md-12 col-lg-12">
          <table class="table table-dark">
              <thead>
                <tr>
                  <th scope="col">request date</th>
                  <th scope="col">Company name <br>& Id</th>
                  <th scope="col">Email</th>
                  <th scope="col">Address</th>
                  <th scope="col">Mobile</th>
                  <th scope="col">Bank details <br>Bank name <br> Account no <br>Ifsc</th>
                  <th scope="col">Status</th>
                </tr>
              </thead>
              <tbody>
                {% for reseller in resellers %}
                <form action="" method="post">
                  {% csrf_token %}
                <tr>
                <td>{{reseller.request_date|date:'Y-m-d'}}</td>
                <td>{{reseller.company_name}}<br>{{reseller.reg_id}}</td>
                <td>{{reseller.email}}</td>
                <td>{{reseller.address}}</td>
                <td>{{reseller.mobile}}</td>
                <td>{{reseller.branch_bank}} <br> {{reseller.account_number}} <br>{{reseller.ifsc_code}} </td>
                <td>{{reseller.status}}</td>
              </tr></form>
                {% endfor %}
                
              </tbody>
            </table>




      </div>
  </div>
</div>




{% endblock %}

learn_app/admin1/templates/admin1/sum.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
  
    <form action="" method="post">
        {% csrf_token %}
<label for="">first num :</label>
<input type="text" name="frstnum" id=""><br><br>
<label for="">second num :</label>
<input type="text" name="scndnum" id=""><br><br>
<button>findsum</button><br><br>

<label for="">sum :</label>
<input type="text" name="sumis" id="" value="{{res}}">


    </form>
</body>
</html>