learn_app/admin1/urls.py
from django. urls import path
from . import views
app_name= 'admin1'

urlpatterns = [
    path('homepage/',views.getadmin1,name="homepage"),
    path('master3/',views.getmaster3,name="master3"),
    path('manageresellers/',views.getmanageresellers,name="manageresellers"),
    path('activeresellers/',views.getactiveresellers,name="activeresellers"),
    path('rejectedresellers/',views.getrejectedresellers,name="rejectedresellers"),
    path('sum/',views.getsum,name="sum"),
]

learn_app/learn_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin1/', include('admin1.urls')),
    path('reseller/', include('reseller.urls')),
    path('customer/', include('customer.urls')),
]+static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

learn_app/reseller/urls.py
from django. urls import path
from . import views
app_name = 'reseller'

urlpatterns = [
    path('homepage2/',views.gethomepage2,name="homepage2"),
    path('login1/',views.getlogin1,name="login1"),
    path('signup1/',views.getsignup1,name="signup1"),
    path('addproduct/',views.getaddproduct,name="addproduct"),
    path('master/',views.getmaster,name="master"),
    path('edit/',views.getedit,name="edit"),   
    path('myproducts/',views.getmyproducts,name="myproducts"), 
    path('account/',views.getaccount,name="account"),   
    path('vieworders/',views.getvieworders,name="vieworders"),
    # path('updateproduct/<int:s_id>',views.update_products,name="updateproducts"),   
    # path('deleteproduct/<int:s_id>',views.delete_products,name="deleteproducts"),  
    path('viewproducts_demo',views.getviewproducts_demo,name="viewproducts_demo"),
    path('deleteproducts/<int:p_id>',views.deleteproducts,name="delete_product"),    
    path('updation_demo/<int:p_id>',views.getupdationdemo,name="_updationdemo"),

   ]

learn_app/reseller/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class Reseller(models.Model):
    company_name=models.TextField(max_length=50,db_column='reseller_company_name')
    reg_id=models.TextField(max_length=50,db_column='company_reg_id')
    account_number=models.TextField(max_length=50,db_column='bank_account_number')
    ifsc_code=models.TextField(max_length=50,db_column='bank_ifsc_code')
    branch_bank=models.TextField(max_length=50,db_column='bank_branch_name')
    address=models.TextField(max_length=50,db_column='company_address')
    country=models.TextField(max_length=50,db_column='company_country')
    mobile=models.TextField(max_length=50,db_column='mobile_number')
    email=models.TextField(max_length=50,db_column='company_email')
    user_id=models.IntegerField(null=True,db_column='login_id')
    password= models.TextField(max_length=50,db_column='pass_word')
    otp= models.TextField(max_length=50,db_column='company_otp')
    status=models.TextField(max_length=50,default="inactive",db_column='company_status')
    request_date=models.DateField(default=datetime.now,db_column='request_date')  


    class Meta:
        db_table='reseller'

class Add_product(models.Model):
    title=models.TextField(max_length=50,db_column='pro_title')
    pro_id=models.TextField(max_length=50,db_column='registerd_pro_id')
    discription=models.TextField(max_length=100,db_column='pro_discription')
    pro_picture=models.ImageField(upload_to='product_images/',db_column='pro_pictures')
    price=models.IntegerField(db_column='pro_price')
    quantity=models.IntegerField(db_column='pro_quantity')
    weight=models.IntegerField(db_column='pro_weight')
    weight_unit=models.TextField(max_length=50,db_column='pro_weight_unit')
    catagory=models.TextField(max_length=50,db_column='pro_catagory')
    sub_catagory=models.TextField(max_length=50,db_column='pro_sub_catagory')
    brand=models.TextField(max_length=50,db_column='pro_brand')
   # Status=models.TextField(max_length=50,null=True,db_column='pro_status')
    reseller=models.ForeignKey(Reseller,on_delete=models.CASCADE,null=True,db_column='reseller')

    class Meta:
        db_table='add_product'   

learn_app/reseller/views.py
from django.shortcuts import render,redirect
from .models import *
from django.conf import settings
# Create your views here.

def gethomepage2(request):
    return render(request,"reseller/homepage2.html")

def getlogin1 (request):
    return render(request,"reseller/login1.html")
 
def getsignup1(request):
    return render(request,"reseller/signup1.html")
 
def getaddproduct(request):
    if request.method=='POST':
        p_title=request.POST['_title']
        p_regid=request.POST['_Registered_product_id']
        p_discription=request.POST['_discription']
        p_picture=request.FILES['_picture']
        p_price=request.POST['_price']
        p_quantity=request.POST['_quantity']
        p_weight=request.POST['_weight']
        p_weightunit=request.POST['_weight_unit']
        p_catagory=request.POST['_catagory']
        p_subcatagory=request.POST['_subcatagory']
        p_brand=request.POST['_brand']
        #p_status=request.POST['_status']
        p_resellerid=Reseller.objects.get(id=request.session['seller_id'])
        product_exists=Add_product.objects.filter(pro_id=p_regid)
        if not product_exists:

            product=Add_product(title=p_title,pro_id=p_regid,discription=p_discription,pro_picture=p_picture,price=p_price,quantity=p_quantity,weight=p_weight,weight_unit=p_weightunit,catagory=p_catagory,sub_catagory=p_subcatagory,brand=p_brand,reseller=p_resellerid)
            product.save()
            return render(request,"reseller/addproduct.html",{'message':'product added successfully'})
        else:
            return render(request,"reseller/addproduct.html",{'message':'product already exists'})
        
    return render(request,"reseller/addproduct.html")

def getmaster(request):
    return render(request,"reseller/master.html")

def getedit(request):
    # title1=request.POST['ti_tle']
    # regid1=request.POST['pr_id']
    # discription1=request.POST['pr_ad']
    # picture1=request.FILES['pr_im']
    # price1=request.POST['pr_price']
    # quantity1=request.POST['pr_quant']
    # weight1=request.POST['pr_weight']
    # weightunit1=request.POST['pr_unit']
    # catagory1=request.POST['pr_cat']
    # subcatagory1=request.POST['pr_subcat']
    # brand1=request.POST['pr_brand']
    
    # prod=Add_product.objects.get(title=title1,pro_id=regid1,discription=discription1,pro_picture=picture1,price=price1,quantity=quantity1,weight=weight1,weight_unit=weightunit1,catagory=catagory1,sub_catagory=subcatagory1,brand=brand1)

    return render(request,"reseller/edit.html")

def getmyproducts(request):
    products=Add_product.objects.all()
   
    return render(request,"reseller/myproducts.html",{'product_data':products})

def getaccount(request):
    return render(request,"reseller/account.html")
 
def getvieworders(request):
    return render(request,"reseller/vieworders.html")

# def update_products(request,s_id):
    
#     title1=request.POST['ti_tle']
#     regid1=request.POST['pr_id']
#     discription1=request.POST['pr_ad']
#     picture1=request.FILES['pr_im']
#     price1=request.POST['pr_price']
#     quantity1=request.POST['pr_quant']
#     weight1=request.POST['pr_weight']
#     weightunit1=request.POST['pr_unit']
#     catagory1=request.POST['pr_cat']
#     subcatagory1=request.POST['pr_subcat']
#     brand1=request.POST['pr_brand']
    
#     Add_product.objects.filter(id=s_id).update(title=title1,pro_id=regid1,discription=discription1,pro_picture=picture1,price=price1,quantity=quantity1,weight=weight1,weight_unit=weightunit1,catagory=catagory1,sub_catagory=subcatagory1,brand=brand1)
    
    
#     product=Add_product.objects.get(id=s_id)
    
    
     
#     return redirect('reseller:edit')

# def delete_products(request,s_id):
#     product=Add_product.objects.get(id=s_id)
#     product.delete()
#     return redirect('reseller:myproducts')   
 
# demo updation deletion
def getviewproducts_demo(request):
    product=Add_product.objects.all()

    return render(request,"reseller/viewproducts_demo.html",{'product_data':product})

def deleteproducts(request,p_id):
    Add_product.objects.get(id=p_id).delete()
    return redirect('reseller:viewproducts_demo')

# end demo updation deletion 


def getupdationdemo(request,p_id):
    if request.method=='POST':
        title_=request.POST['_title']
        prid_=request.POST['_Registered_product_id']
        discription_=request.POST['_discription']
        price_=request.POST['_price']
        quantity_=request.POST['_quantity']
        Add_product.objects.filter(id=p_id).update(title=title_,pro_id=prid_,discription=discription_,price=price_,quantity=quantity_)
        return redirect('reseller:viewproducts_demo')


    product=Add_product.objects.get(id=p_id)
   

    return render(request,"reseller/updationdemo.html",{'product_data':product})

learn_app/reseller/templates/reseller/addproduct.html
{% extends 'reseller/master.html' %}

{% block content %}


{% load static %}

    <div class="container" style="background-color: rgb(199, 227, 227);">
        <div class="row">
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
<h2>Add product</h2>
<form action="{% url 'reseller:addproduct' %}" method="post" enctype="multipart/form-data">
                    
    {% csrf_token  %}                

  
    <div class="form-group">
      <label for="exampleFormControlSelect1">Title</label>
      <input type="text" class="form-control" placeholder="Title of the product" name="_title">
    </div>
    <div class="form-group">
      <label for="exampleFormControlSelect1">Registered product id</label>
      <input type="text" class="form-control" placeholder="product id" name="_Registered_product_id">
    </div>

  


<div class="form-group">
<label for="exampleFormControlTextarea1">Discription </label>
<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="_discription"></textarea>
</div>
<div class="form-group">
  <label for="exampleFormControlSelect1">Upload product pictures</label>
  <input type="file" name="_picture" id=""class="form-control" placeholder="">
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Price </label>
      <input type="text" name="_price" class="form-control" id="" placeholder="0.0">
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1">Quantity </label>
        <input type="text" name="_quantity" id=""class="form-control" placeholder="Available quantity">
        </div>
        <div class="row">
            <div class="col">
              <label for="exampleFormControlSelect1">Weight</label>
              <input type="text" class="form-control" placeholder="0.0" name="_weight">
            </div>
            <div class="col">
              <label for="exampleFormControlSelect1">Weight unit</label>
              <select class="form-control" name="_weight_unit" id="exampleFormControlSelect1">
                <option>kilogram</option>
               <option>gram</option>
               <option>tonne</option>
                       
                 </select>
            </div>
            </div>
            <div class="row">
            <div class="col">
              <label for="exampleFormControlSelect1">Catagory</label>
              <select class="form-control" name="_catagory" id="exampleFormControlSelect1">
                <option>sports</option>
               <option>electronis</option>
               <option>garments</option>
               <option>fashion</option>      
                 </select>
          </div>
          <div class="col">
            <label for="exampleFormControlSelect1">Subcatagory</label>
            <select class="form-control" name="_subcatagory" id="exampleFormControlSelect1">
              <option>ladies</option>
             <option>mens</option>
             <option>children</option>
                     
               </select>
        </div>
        </div>
        <div class="row">
            <div class="col">
              <label for="exampleFormControlSelect1">Brand</label>
              <input type="text"  name="_brand"class="form-control" placeholder="eg:nike">
            </div>
          
           
          </div>
           <div>   
            <br>
            <div class="form-group">
                <button  class="btn btn-primary btn-lg btn-block">Save</button>
            
</form>
</div>
    </div>
    <p>{{message}}</p>
</div>
</div>



{% endblock %}

learn_app/reseller/templates/reseller/homepage2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body style="background-color: #adb5bb;">
   <div class="container" >
    <div class="row">
  
  <div class="col-12 col-sm-12 col-md-12 col-lg-12">
  
      <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
          <a class="navbar-brand"><img src="{% static 'images/LOGO1.jpg' %}" alt="" height="60px" width="100px"></a>
          <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"  style="width:300px;">
            <button style="margin-right:15px;" class="btn btn-outline-success my-2 my-sm-0" type="submit">search</button>
              <button style="margin-right:10px ;width: 100px;" class="btn btn-warning"><a href="{% url 'reseller:login1' %}">log in</a></button>
              <a href="{% url 'reseller:signup1' %}"><button style="  width: 100px;" class="btn btn-warning">sign up</button></a>
          </form>
        </nav>       
      </div>
      <div class="col-12 col-sm-12 col-md-12 col-lg-12">
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(8, 56, 40);">
  
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Electronics
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Mobile&accessories</a>
                  <a class="dropdown-item" href="#">Laptop</a>
                  <a class="dropdown-item" href="#">Speaker</a>
                  <a class="dropdown-item" href="#">Camera</a>
                  <a class="dropdown-item" href="#">Gaming&Accessories</a>
                </div>
              </li>
  
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                  Tv&Appliances
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Television</a>
                  <a class="dropdown-item" href="#">Washing machine</a>
                  <a class="dropdown-item" href="#">Rafrigerators</a>
                  <a class="dropdown-item" href="#">Kitchen&Applainces</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                  Sports
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Football</a>
                  <a class="dropdown-item" href="#">Cricket</a>
                  <a class="dropdown-item" href="#">Tennis</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                  Fashion
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Mens</a>
                  <a class="dropdown-item" href="#">Womens</a>
                  <a class="dropdown-item" href="#">kids</a>
                </div>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    </div>
  </div>


<div class="container">
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12"></div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12">

<a href="">
    <div class="div1" style="padding: 10px;padding-bottom: 20px;margin: 10px;background-color: rgb(30, 111, 203);" >
        <h2 style="color: aliceblue; text-align: center;">U.S POLO ASSN </h2>
        <img class="img-fluid" src="{% static 'images/uss2.jpg' %}" alt="" width="100%">

    </div>
</a>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-12"></div>

<div class="col-9 col-sm-9 col-md-4 col-lg-4">

    <a href="">
        <div style="padding: 5px;padding-bottom: 20px;padding-right:5px; margin:10px;background-color: rgb(30, 111, 203);">
            <h2 style="color: aliceblue;text-align: center;">oppo mobiles</h2>
            <img src="{% static 'images/oppo.jpg' %}" alt="" width="100%" height="300px">
        </div>
    </a>
</div>

<div class="col-9 col-sm-9 col-md-4 col-lg-4">

    <a href="">
        <div style="padding: 5px;padding-bottom: 20px;padding-right:5px; margin:10px;background-color: rgb(30, 111, 203);">
            <h2 style="color: aliceblue;text-align: center;">vivo mobiles</h2>
            <img src="{% static 'images/vivo new.jpg' %}" alt="" width="100%" height="300px">
        </div>
    </a>
</div>
<div class="col-9 col-sm-9 col-md-4 col-lg-4">

    <a href="">
        <div style="padding: 5px;padding-bottom: 20px;padding-right:5px; margin:10px;background-color: rgb(30, 111, 203);">
            <h2 style="color: aliceblue;text-align: center;">samsung mobiles</h2>
            <img src="{% static 'images/samsung1.jpg' %}" alt="" width="100%" height="300px">
        </div>
    </a>
</div>
<div class="col-6 col-sm-6 col-md-6 col-lg-6">

    <a href="">
    <div style="padding: 5px;padding-bottom: 20px;padding-right:5px; margin:10px;background-color: rgb(30, 111, 203);">
        <h2 style="color: aliceblue;text-align: center;">adidas</h2>
        <img src="{% static 'images/adidas.jpg' %}" alt="" width="100%" height="">
    </div>
</a>


</div>
<div class="col-6 col-sm-6 col-md-6 col-lg-6">

    <a href="">
    <div style="padding: 5px;padding-bottom: 20px;padding-right:5px; margin:10px;background-color: rgb(30, 111, 203);">
        <h2 style="color: aliceblue;text-align: center;">nike</h2>
        <img src="{% static 'images/nike1.jpg' %}" alt="" width="100%" height="">
    </div>
</a>
</div>

<div style="background-color: rgb(179, 174, 174);" class="col-12 col-sm-12 col-md-6 col-lg-6">
    <h6>REGISTERED OFFICE ADDRESS</h6>
    <P>5th floor,crafit square,hilite buisiness park,<br>
    thondayadu,poovangal,kozhikode,kerala,670136
    </P>
</div>
<div style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2"><H6>POLICY</H6>
<p>return policy,  <br> terms of use<br> security <br> privacy</p>
</div>
<div style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2">
    <h6>ABOUT AS</h6>
    <p> contact us <br> about as<br> careers<br> cybersquare<br> wholesale </p>
</div>
<div  style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2">
    <h6>SOCIAL</h6>
    <p>facebook<br> twitter<br> youtube</p>
</div>
<div style="background-color: rgb(117, 121, 121);" class="col-2 col-sm-3 col-md-4 col-lg-4"></div>
    <div style="background-color: rgb(117, 121, 121);" class="col-8 col-sm-6 col-md-4 col-lg-4">
        <img src="{% static 'images/visa.jpg' %}" alt=""height="75px" width="200px">
    </div>
    <div style="background-color: rgb(117, 121, 121);" class="col-2 col-sm-3 col-md-4 col-lg-4"></div>


</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>      


</body>
</html>

learn_app/reseller/templates/reseller/login1.html
{% extends 'customer/master1.html' %}

{% block content %}

{% load static %}
<div class="container">
<div class="row">
    <div class="col- col-sm- col-md-4 col-lg-4"></div>
        <div class="col-12 col-sm-12 col-md-8 col-lg-8">
            for
                <h2>Log in</h2>
                <div class="form-group">
                  <label for="exampleInputEmail1">User name</label>
                  <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                  
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input type="password"name="password" class="form-control" id="exampleInputPassword1">
                </div>
                
                <button type="submit" class="btn btn-success">log in</button><br><br>

                <a href="">forget password ?</a><br><br>
                <a href="">create an account</a><br> <br>

              </form>
        </div>




      

</div>
</div>   



{% endblock %}

learn_app/reseller/templates/reseller/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
  <div class="container" >
    <div class="row">
  
  <div class="col-12 col-sm-12 col-md-12 col-lg-12">
  
      <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
          <a class="navbar-brand"><img src="{% static 'images/LOGO1.jpg' %}" alt="" height="60px" width="100px"></a>
          
  
            
            <div class="dropdown">
              <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                  <img src="{% static 'images/profilelogo.jpg' %}" alt=""style="width:50px; height:50px;">
                </button>
              <div class="dropdown-menu">
                <button class="dropdown-item" type="button">Manage Account</button>
                <button class="dropdown-item" type="button">Log out</button>
              </div>
              </div>
            </div>
        </nav>       
      </div>
      <div class="col-12 col-sm-12 col-md-12 col-lg-12">
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(34, 73, 73);">
  
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'reseller:vieworders' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:addproduct' %}">Add products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reseller:myproducts' %}">My products</a>
            </li>
            
            
            
            
          </ul>
        </div>
      </nav>
    </div>



</div>
</div>


{% block content %}
{% endblock %}

<div class="container">
  <div class="row">
       

<div style="background-color: rgb(179, 174, 174);" class="col-12 col-sm-12 col-md-6 col-lg-6">
<h6>REGISTERED OFFICE ADDRESS</h6>
<P>5th floor,crafit square,hilite buisiness park,<br>
thondayadu,poovangal,kozhikode,kerala,670136
</P>
</div>
<div style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2"><H6>POLICY</H6>
<p>return policy,  <br> terms of use<br> security <br> privacy</p>
</div>
<div style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2">
<h6>ABOUT AS</h6>
<p> contact us <br> about as<br> careers<br> cybersquare<br> wholesale </p>
</div>
<div  style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2">
<h6>SOCIAL</h6>
<p>facebook<br> twitter<br> youtube</p>
</div>
<div style="background-color: rgb(117, 121, 121);" class="col-2 col-sm-3 col-md-4 col-lg-4"></div>
<div style="background-color: rgb(117, 121, 121);" class="col-8 col-sm-6 col-md-4 col-lg-4">
  <img src="{% static 'images/visa.jpg' %}" alt=""height="75px" width="200px">
</div>
<div style="background-color: rgb(117, 121, 121);" class="col-2 col-sm-3 col-md-4 col-lg-4"></div>
</div>

</div>



<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>      
</body>
</html>

learn_app/reseller/templates/reseller/vieworders.html
{% extends 'reseller/master.html' %}

{% block content %}

{% load static %}








{% endblock %}

learn_app/reseller/templates/reseller/viewproducts_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <table border="1">
<tr>
    <th>title</th>
    <th>id</th>
    <th>description</th>
    <th>price</th>
    <th>quantity</th>
    <th>catagory</th>
    <th>delete</th>
    <th>update</th>
</tr>
{% for product in product_data %}
<tr>
    <!-- <form action="" method="post">
     {% csrf_token %}
     -->

<td>{{product.title}}</td>
<td>{{product.pro_id}}</td>
<td>{{product.discription}}</td>
<td>{{product.price}}</td>
<td>{{product.quantity}}</td>
<td>{{product.catagory}}</td>
<td><a href="{% url 'reseller:delete_product' product.id %}">delete</a></td>

<td> <a href="{% url 'reseller:_updationdemo' product.id%}"> update</a></td>
</tr>
<!-- </form> -->
{% endfor %}
   </table> 

</body>
</html>