learn_app/admin1/urls.py
from django. urls import path
from . import views
app_name= 'admin1'

urlpatterns = [
    path('homepage/',views.getadmin1,name="homepage"),
    path('master3/',views.getmaster3,name="master3"),
    path('manageresellers/',views.getmanageresellers,name="manageresellers"),
    path('activeresellers/',views.getactiveresellers,name="activeresellers"),
    path('rejectedresellers/',views.getrejectedresellers,name="rejectedresellers"),
    path('sum/',views.getsum,name="sum"),
]

learn_app/customer/urls.py
from django. urls import path
from . import views
app_name='customer'

urlpatterns = [
    path('master1/',views.getmaster,name="master1"),
    path('homepage1/',views.getcustomerhomepage,name="homepage1"),
    path('signup/',views.getcustomersignup,name="signup"),
    path('verifyotp/',views.getcustomerverifyotp,name="verifyotp"),
    path('login/',views.getcustomerlogin,name="login"),
    path('profile/',views.getcustomerprofile,name="profile"),
    path('search/',views.getcustomers,name="search"),
    path('master2/',views.getmaster2,name="master2"),
    path('viewproduct/',views.getviewproduct,name="viewproduct"),
    path('loginhomepage/',views.getloginhomepage,name="loginhomepage"),
    path('bag/',views.getbag,name="bag"),
    path('buynow/',views.getbuynow,name="buynow"),
]

learn_app/learn_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin1/', include('admin1.urls')),
    path('reseller/', include('reseller.urls')),
    path('customer/', include('customer.urls')),
]+static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

learn_app/customer/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    first_name=models.TextField(max_length=30,db_column='f_name')
    last_name=models.TextField(max_length=30,db_column='l_name')
    gender=models.CharField(max_length=6,db_column='gender')
    dateofbirth=models.DateField(db_column='date_of_birth')
    address=models.TextField(max_length=100,db_column='address')
    country=models.TextField(max_length=20,db_column='country')
    mobilenumber=models.TextField(max_length=20,db_column='mob_num')
    email=models.TextField(max_length=20,db_column='email')
    password=models.TextField(max_length=15,db_column='password')
    otp=models.CharField(max_length=100,db_column='otp')
    status=models.TextField(max_length=20,default="",db_column='status')
    
    class Meta:
        db_table='customer'

learn_app/customer/views.py
from django.shortcuts import render,redirect
from .models import *
from random import randint
from django.core.mail import send_mail 
from django.conf import settings
from reseller.models import Add_product
from reseller.models import Reseller
# Create your views here.


def getmaster(request):
    return render(request,"customer/master1.html")
    
def getcustomerhomepage(request):
    return render(request,"customer/homepage1.html")

def getcustomersignup(request):
    msg=""
    if request.method=='POST':
        user_type=request.POST['usertype']
        if user_type=='customer':
            c_firstname=request.POST['_firstname']
            c_lastname=request.POST['_lastname']
            c_gender=request.POST['_gender']
            c_dateofbirth=request.POST['_dateofbirth']
            c_address=request.POST['_address']
            c_country=request.POST['_country']
            c_mobilenumber=request.POST['_mobilenumber']
            c_email=request.POST['_email']
            c_password=request.POST['_password']
            customer_exists=Customer.objects.filter(email=c_email).exists()

            if not customer_exists:
                otp=randint(1000,9999)
                send_mail(
                    'please verify your otp',
                    str(otp),
                    settings.EMAIL_HOST_USER,
                    [c_email],

                )
                customer_data=Customer(first_name=c_firstname,last_name=c_lastname,gender=c_gender,dateofbirth=c_dateofbirth,address=c_address,country=c_country,mobilenumber=c_mobilenumber,email=c_email,password=c_password,otp=str(otp),status='otpverify')
                customer_data.save()
                customer=Customer.objects.get(email=c_email)
                request.session['customer_id']=customer.id

                # msg='customer registerd successfully'
                return redirect('customer:verifyotp') 
    #           return render(request,'customer/signup.html',{'message':msg})
        if user_type=='reseller':
            r_company_name=request.POST['_company_name']
            r_company_id=request.POST['reg_id']
            r_account_num=request.POST['_account_no']
            r_ifsc_code=request.POST['_ifsc_code']
            r_bank_name=request.POST['_branch_name']
            r_address=request.POST['_address']
            r_country=request.POST['_country']
            r_mobilenumber=request.POST['_mobilenumber']
            r_email=request.POST['_email']
            r_password=request.POST['_password']
            r_loginid=randint(1000,9999)
            reseller_exists=Reseller.objects.filter(email=r_email).exists()
            if not reseller_exists:
                reseller=Reseller(company_name=r_company_name,reg_id=r_company_id,account_number=r_account_num,ifsc_code=r_ifsc_code,address=r_address,country=r_country,mobile=r_mobilenumber,email=r_email,user_id=r_loginid,password=r_password)
                reseller.save()
                subject='your login id is '+str(r_loginid)
                send_mail(
                    'login credentials',
                    subject,
                    settings.EMAIL_HOST_USER,
                    [r_email],

                )
                msg='registration successful'
            else:
                msg='email exists'
            return render(request,'customer/signup.html',{'message':msg})
    return render(request,"customer/signup.html")




def getcustomerverifyotp(request):
    if request.method=='POST':
        otp=request.POST['o_tp']
        c_id=request.session['customer_id']
        data=Customer.objects.get(id=c_id)
        if otp==data.otp:
            Customer.objects.filter(id=c_id).update(status='active')
            return redirect('customer:loginhomepage')
        else:
            return render(request,"customer/verifyotp.html",{'message':'invalid otp'})

    return render(request,"customer/verifyotp.html")

 
def getcustomerlogin(request):
    if request.method=="POST":
        _username=request.POST['username']
        _password=request.POST['password']
        if '@' in _username:
            customer_exist=Customer.objects.filter(email=_username,password=_password).exists()
            if customer_exist:
                customer=Customer.objects.get(email=_username,password=_password)
                request.session['customer_id']=customer.id
                if customer.status=='otpverify':
                    otp=randint(1000,9999)
                    send_mail(
                    'please verify your otp',
                    str(otp),
                    settings.EMAIL_HOST_USER,
                    [customer.email],
                
                    )

                    customer.otp=otp
                    customer.save()
                    return redirect('customer:verifyotp')
                return redirect('customer:loginhomepage')
            else:
                return render(request,"customer/login.html",{'message':'invalid user details'})

        elif _username.isdigit():
            seller_exist=Reseller.objects.filter(user_id=_username,password=_password).exists()
            
            if seller_exist:
                seller_data=Reseller.objects.get(user_id=_username,password=_password)
                if seller_data.status=='active':
                    request.session['seller_id']=seller_data.id
                    return redirect('reseller:homepage2')
                else:
            
            
                    return render(request,"customer/login.html",{'message':'account not approved'})
            else:
                return render(request,"customer/login.html",{'message':'invalid user name or password'})
    return render(request,"customer/login.html")

def getcustomerprofile(request):
    return render(request,"customer/profile.html")

def getcustomers(request):
    return render(request,"customer/search.html")

def getmaster2(request):
    return render(request,"customer/master2.html")

def getviewproduct(request):
    return render(request,"customer/viewproduct.html")

def getloginhomepage(request):
    products=Add_product.objects.all()
    return render(request,"customer/loginhomepage.html",{'product_data':products})

def getbag(request):
    return render(request,"customer/bag.html")

def getbuynow(request):
    return render(request,"customer/buynow.html")

learn_app/customer/templates/customer/bag.html
{% extends 'customer/master2.html' %}


{% block content %}

{% load static %}
<div class="container">
<div class="row">
<div class="col-12 col-sm-12 col-md-12 col-lg-12">
<h1>Your Bag</h1>
   
    <div class="card text-center">
        <div class="card-header">
          <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
              <h4>image</h4>
            </li>
            
          </ul>
        </div>
        <div class="card-body">
          <img src="{% static 'images/lap3.jpg' %}" alt=""  height="200px"width="200px" >
          <label for="">product</label>
          <input type="text" name="" id="">
          <label for="">Quantity</label>
          <input type="text" name="" id="">
          <label for="">price</label>
          <input type="text" name="" id=""><br>
          <label for="">total-amount</label>
          <input type="text" name="" id=""><br><br>
          <button type="button" class="btn btn-success">Checkout</button>
        </div>
      </div>
</div>
</div>
</div>






{% endblock %}

learn_app/customer/templates/customer/buynow.html
{% extends 'customer/master2.html' %}

{% block content %}

{% load static %}

<div class="container">
    <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
    <h1>Your Bag</h1>
       
        <div class="card text-center">
            <div class="card-header">
              <ul class="nav nav-pills card-header-pills">
                <li class="nav-item">
                  <h4>image</h4>
                </li>
                
              </ul>
            </div>
            <div class="card-body">
              <img src="{% static 'images/lap3.jpg' %}" alt=""  height="200px"width="200px" >
              <label for="">product</label>
              <input type="text" name="" id="">
              <label for="">Quantity</label>
              <input type="text" name="" id="">
              <label for="">price</label>
              <input type="text" name="" id=""><br>
              <label for="">total-amount</label>
              <input type="text" name="" id=""><br><br>
                <label for="">Methode of pay</label>
                <input type="radio" name="" id="">Cash on delivary
                <input type="radio" name="" id="">Google pay
                <input type="radio" name="" id="">
<br>
                <label for="">Address:</label>
                <textarea name="" id="" cols="30" rows="10"></textarea>

<br>


              <button type="button" class="btn btn-success">Buy now</button>
            </div>
          </div>
    
    
    
    
    
    
    </div>
    
    
    
    </div>
    
    
    </div>
    
    
    












{% endblock %}

learn_app/customer/templates/customer/login.html
{% extends 'customer/master1.html' %}

{% block content %}

{% load static %}
<div class="container">
<div class="row">
    <div class="col- col-sm- col-md-4 col-lg-4"></div>
        <div class="col-12 col-sm-12 col-md-8 col-lg-8">
            <form action="{% url 'customer:login' %}" method="post">
              {% csrf_token %}
                <h2>Log in</h2>
                <div class="form-group">
                  <label for="exampleInputEmail1">User name</label>
                  <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                  
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                </div>
                
                <button  class="btn btn-success">log in</button><br><br>

                <a href="">forget password ?</a><br><br>
                <a href="">create an account</a><br> <br>

              </form>
        </div>

<p>{{message}}</p>

{% endblock %}

learn_app/customer/templates/customer/loginhomepage.html
{% extends 'customer/master2.html' %}

{% block content %}

{% load static %}
<style>
.container{
    background-color: rgb(49, 90, 186);
}
h2,h5{
    color: rgb(54, 116, 95);
  }
  .card-text{
    color: brown;
  }
</style>


<div class="container">
<div class="row">

    {% for product in product_data %}
   
<div class="col-md-4">

    <a href="{% url 'customer:viewproduct' %}">
    <div class="card" style="width: 22rem;">
      <img src="/media/{{product.pro_picture}}" class="card-img-top" alt="" height="300px" width="300px">
      <div class="card-body">
        <h5 class="card-title">{{product.title}}</h5>
        <p class="card-text">{{product.discription}}
          {{product.price}}</p>
          <button class="btn btn-danger">buy now</button> 
      </div>
    </div>
    </a>
    </div>




{% endfor %}

</div>
</div>
{% endblock %}

learn_app/customer/templates/customer/master1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body style="background-color: #adb5bb;">
<div class="container" >
  <div class="row">

<div class="col-12 col-sm-12 col-md-12 col-lg-12">

    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand"><img src="{% static 'images/LOGO1.jpg' %}" alt="" height="60px" width="100px"></a>
        <form class="form-inline">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"  style="width:300px;">
          <button style="margin-right:15px;" class="btn btn-outline-success my-2 my-sm-0" type="submit"> <a href="{% url 'customer:search' %}">search</a> </button>
            <button style="margin-right:10px ;width: 100px;" class="btn btn-warning"><a href="{% url 'customer:login' %}">log in </a></button>
            <button style="  width: 100px;" class="btn btn-warning"><a href="{% url 'customer:signup' %}">Sign up</a></button>
        </form>
      </nav>       
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(8, 56, 40);">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
              Electronics
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Mobile&accessories</a>
                <a class="dropdown-item" href="#">Laptop</a>
                <a class="dropdown-item" href="#">Speaker</a>
                <a class="dropdown-item" href="#">Camera</a>
                <a class="dropdown-item" href="#">Gaming&Accessories</a>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Tv&Appliances
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Television</a>
                <a class="dropdown-item" href="#">Washing machine</a>
                <a class="dropdown-item" href="#">Rafrigerators</a>
                <a class="dropdown-item" href="#">Kitchen&Applainces</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Sports
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Football</a>
                <a class="dropdown-item" href="#">Cricket</a>
                <a class="dropdown-item" href="#">Tennis</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Fashion
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Mens</a>
                <a class="dropdown-item" href="#">Womens</a>
                <a class="dropdown-item" href="#">kids</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
  </div>
  </div>
</div>

{% block content %}
{% endblock %}



<div class="container">
  <div class="row">
       

<div style="background-color: rgb(179, 174, 174);" class="col-12 col-sm-12 col-md-6 col-lg-6">
<h6>REGISTERED OFFICE ADDRESS</h6>
<P>5th floor,crafit square,hilite buisiness park,<br>
thondayadu,poovangal,kozhikode,kerala,670136
</P>
</div>
<div style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2"><H6>POLICY</H6>
<p>return policy,  <br> terms of use<br> security <br> privacy</p>
</div>
<div style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2">
<h6>ABOUT AS</h6>
<p> contact us <br> about as<br> careers<br> cybersquare<br> wholesale </p>
</div>
<div  style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2">
<h6>SOCIAL</h6>
<p>facebook<br> twitter<br> youtube</p>
</div>
<div style="background-color: rgb(117, 121, 121);" class="col-2 col-sm-3 col-md-4 col-lg-4"></div>
<div style="background-color: rgb(117, 121, 121);" class="col-8 col-sm-6 col-md-4 col-lg-4">
  <img src="{% static 'images/visa.jpg' %}" alt=""height="75px" width="200px">
</div>
<div style="background-color: rgb(117, 121, 121);" class="col-2 col-sm-3 col-md-4 col-lg-4"></div>
</div>

</div>






            
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>      


</body>
</html>

learn_app/customer/templates/customer/master2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>      


  </head>

<body style="background-color: #adb5bb;">
<div class="container" >
  <div class="row">

<div class="col-12 col-sm-12 col-md-12 col-lg-12">

    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand"><img src="{% static 'images/LOGO1.jpg' %}" alt="" height="60px" width="100px"></a>
        <form class="form-inline">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"  style="width:300px;">
          <button style="margin-right:15px;" class="btn btn-outline-success my-2 my-sm-0" type="submit"> <a href="{% url 'customer:search' %}">search</a> </button>
          <div class="dropdown">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                <img src="{% static 'images/profilelogo.jpg' %}" alt=""style="width:50px; height:50px;">
              </button>
            <div class="dropdown-menu">
              <button class="dropdown-item" type="button">View profile</button>
              <button class="dropdown-item" type="button">View bag</button>
              <button class="dropdown-item" type="button">View orders</button>
              <button class="dropdown-item" type="button">Change password</button>
              <button class="dropdown-item" type="button">Log out</button>
            </div>
          </div>
      </nav>        
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(8, 56, 40);">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
              Electronics
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Mobile&accessories</a>
                <a class="dropdown-item" href="#">Laptop</a>
                <a class="dropdown-item" href="#">Speaker</a>
                <a class="dropdown-item" href="#">Camera</a>
                <a class="dropdown-item" href="#">Gaming&Accessories</a>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Tv&Appliances
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Television</a>
                <a class="dropdown-item" href="#">Washing machine</a>
                <a class="dropdown-item" href="#">Rafrigerators</a>
                <a class="dropdown-item" href="#">Kitchen&Applainces</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Sports
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Football</a>
                <a class="dropdown-item" href="#">Cricket</a>
                <a class="dropdown-item" href="#">Tennis</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Fashion
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Mens</a>
                <a class="dropdown-item" href="#">Womens</a>
                <a class="dropdown-item" href="#">kids</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
  </div>
  </div>
</div>

{% block content%}
{% endblock %}


<div class="container">
  <div class="row">
       

<div style="background-color: rgb(179, 174, 174);" class="col-12 col-sm-12 col-md-6 col-lg-6">
<h6>REGISTERED OFFICE ADDRESS</h6>
<P>5th floor,crafit square,hilite buisiness park,<br>
thondayadu,poovangal,kozhikode,kerala,670136
</P>
</div>
<div style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2"><H6>POLICY</H6>
<p>return policy,  <br> terms of use<br> security <br> privacy</p>
</div>
<div style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2">
<h6>ABOUT AS</h6>
<p> contact us <br> about as<br> careers<br> cybersquare<br> wholesale </p>
</div>
<div  style="background-color: rgb(179, 174, 174);" class="col-4 col-sm-4 col-md-2 col-lg-2">
<h6>SOCIAL</h6>
<p>facebook<br> twitter<br> youtube</p>
</div>
<div style="background-color: rgb(117, 121, 121);" class="col-2 col-sm-3 col-md-4 col-lg-4"></div>
<div style="background-color: rgb(117, 121, 121);" class="col-8 col-sm-6 col-md-4 col-lg-4">
  <img src="{% static 'images/visa.jpg' %}" alt=""height="75px" width="200px">
</div>
<div style="background-color: rgb(117, 121, 121);" class="col-2 col-sm-3 col-md-4 col-lg-4"></div>
</div>

</div>






  







            
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>      


</body>
</html>

learn_app/customer/templates/customer/verifyotp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <h1>otp verification</h1>
<label for="">please enter your otp :</label>
<input type="text" name="o_tp" id="">
<button>verify otp</button>
</form>
<p>{{message}}</p>










    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>      
        
</body>
</html>